include_recipe 'prometheus::user'
include_recipe 'prometheus::config'
include_recipe 'prometheus::rules'
include_recipe 'prometheus::backup'
include_recipe 'prometheus::container'
include_recipe 'prometheus::exporters'
include_recipe 'prometheus::alertmanager'
