source 'https://supermarket.chef.io'

cookbook 'prometheus_exporters', git: 'https://github.com/evilmartians/chef-prometheus-exporters'
cookbook 'common', path: '../common'
cookbook 'plex', path: '../plex'

cookbook 'docker'

metadata
