platforms:
  - name: debian-9
    driver: vagrant

suites:
  - name: default
    run_list:
      - recipe[nginx]
    attributes:
      nginx:
        servers:
          - name: cats.lan
            port: 8080
          - name: dogs.lan
            port: 8081
