name 'prometheus'
maintainer 'Colin Douch'
maintainer_email 'colin@quirl.co.nz'
license 'all_rights'
description 'Installs/Configures prometheus via docker'
long_description 'Installs/Configures prometheus via docker'
version '0.1.0'

depends 'docker'
depends 'poise-python'